# Generated by Django 4.2.1 on 2023-06-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_cursol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursol',
            name='img',
            field=models.ImageField(upload_to='static/%y/%m/%d/'),
        ),
    ]
