# Generated by Django 4.2.1 on 2023-07-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_cursol_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/%y/%m/%d/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('quotes', models.TextField()),
            ],
        ),
    ]
