# Generated by Django 4.2.1 on 2023-07-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_alter_about_photo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_photo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imges/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('quotes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_photo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imges/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('quotes', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='about_photo',
            new_name='about_photo1',
        ),
    ]
