# Generated by Django 4.2.1 on 2023-07-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0016_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
