"""
Django settings for emp_ms project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+vdam*%i6ja7&ssf&2uqdavo01*y#1&cvvnp*s!e0b7k3l-%kt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'emp',
    'django.contrib.sites',
    'allauth',  # for social accounts connections
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
]

# ------------------------------
AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',  # for social accoutns backend
                           'allauth.account.auth_backends.AuthenticationBackend', )


SITE_ID = 2  # default site id=1
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'



SOCIALACCOUNT_PROVIDERS = {'google': {
    'SCOPE': ['profile', 'email', ], 'AUTH_PARAMS': {'access_type': 'online', }}}
# after appied migrations
# ------------------------------------
ROOT_URLCONF = 'emp_ms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [r'C:\Users\Admin\.vscode\Frontend work\Django\emp_ms\emp\template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'emp_ms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR/'staticfiles'
STATICFILES_DIRS = (
    BASE_DIR, 'static'
)

# MEDIA_URL = 'http://127.0.0.1:8000/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django session time out
AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(minutes=10),
    'SESSION_TIME': timedelta(minutes=10),
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}  # logout after 10 minutes of downtime


#Email sendig
# EMAIL_HOST='smtp.gmail.com'
# EMAIL_HOST_USER='abhishekrathod9318@gmail.com'
# EMAIL_HOST_PASSWORD='pimbgknfdgcowshm'  #this password generated by less password from google perticular account
# EMAIL_PORT=587
# EMAIL_USER_TLS= True
# EMAIL_USE_SSL = True

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # or 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_SECURE = True  # Set to True if using HTTPS


# import socket
# socket.setdefaulttimeout(10)  # Set a 10-second timeout

# settings.py

# ... other settings ...

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abhishekrathod9318@gmail.com'  # Replace with your email address
EMAIL_HOST_PASSWORD = 'pimbgknfdgcowshm'  #this password generated by less password from google perticular account

#--------otp solution

# settings.py

# Default session timeout (e.g., 15 minutes)
SESSION_COOKIE_AGE = 60 * 15

# Long-lasting session timeout (e.g., 30 days)
LONG_SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
