# Generated by Django 4.2.1 on 2023-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_about_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_photo',
            name='img',
            field=models.ImageField(upload_to='about_photos/'),
        ),
    ]
